# Generated by Django 4.2.4 on 2023-08-24 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParcelType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("EL", "Electronics"),
                            ("CL", "Clothes"),
                            ("OT", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Parcel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=8)),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "delivery_cost",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="parcel.parceltype",
                    ),
                ),
            ],
        ),
    ]
